### PR TITLE
super-early-draft arviz jupyter book

### PR DESCRIPTION
**Pull request by aloctavodia**
May be we can use [jupyter notebook](https://jupyter.org/jupyter-book/intro.html) for the NumFOCUS project, not sure about all the features and possible caveats of this approach, but I think people general likes bookdown and this is the Python equivalent. Not sure if all this files are necessary I created the project from a demo and then delete many files. 

There are only two files that about the content of the _book_, `intro.md` and `Section_01.ipynb` both inside the content folder. Both are very early drafts.

### CODE REVIEW

**Comment by canyon289** [comment]
Jupyterbooks would be great! I haven't had a chance to review code but am curious structure for book.

Previously for this repo I was going to do extensive documentation for each function, and model, but didn't get very far :( 

For book what would we like to do? Chapter on each function or something different entirely?

**Comment by aloctavodia** [comment]
according to the proposal we should have five chapters:

Section 01 Intro to Visualization
Section 02 Diagnostics
Section 03 Model criticism
Section 04 Model comparison
Section 05 Preparation of result for particular audience

Of course we can change everything at this point

**Comment by aloctavodia** [comment]
Probably a good strategy is to subdivide each section into subsections, some of these subsections could be about "extensive documentation for each function", other  could be a general intro/outro (per subsection). Dividing the content into subsection will allow for easier contribution, reviews and maintenance. And is also something supported by jupyter book (see toc.yml file)

**Comment by canyon289** [comment]
I am up for anything!

**Pull request merged**
